/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/env.generated.d.ts` (hash: 32f22b1afb1c41a4c43a6c245792a57d)
interface __BaseEnv_Env {
	AI: Ai;
	CF_VERSION: WorkerVersionMetadata;
	BUILD_VERSION: "development";
	SOURCE_COMMIT: "development";
	HELLO_AGENT: Workflow<Parameters<import("./index").HelloAgentWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BUILD_VERSION" | "SOURCE_COMMIT">> {}
}
